import { Column, Entity, Index, Unique } from 'typeorm';
import { BaseEntity } from './base.entity';

export enum TaskStatus {
  BACKLOG = 'BACKLOG',
  TODO = 'TODO',
  IN_PROGRESS = 'IN_PROGRESS',
  WAITING_ON_CLIENT = 'WAITING_ON_CLIENT',
  OVERDUE = 'OVERDUE',
  DONE = 'DONE',
}

export enum TaskPriority {
  LOW = 'LOW',
  NORMAL = 'NORMAL',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum LinkedEntityType {
  SUBSCRIPTION = 'SUBSCRIPTION',
  INVOICE = 'INVOICE',
  COMPLIANCE = 'COMPLIANCE',
  MANUAL = 'MANUAL',
}

@Entity({ name: 'tasks' })
@Unique('uq_tasks_idem', [
  'organizationId',
  'linkedEntityType',
  'linkedEntityId',
  'cycleKey',
])
export class Task extends BaseEntity {
  @Index()
  @Column({ type: 'char', length: 36, name: 'organization_id' })
  organizationId!: string;

  @Column({ type: 'char', length: 36, name: 'client_id', nullable: true })
  clientId?: string | null;

  @Column({ type: 'varchar', length: 255 })
  title!: string;

  @Column({ type: 'text', nullable: true })
  description?: string | null;

  @Column({ type: 'enum', enum: TaskStatus, default: TaskStatus.TODO })
  status!: TaskStatus;

  @Column({ type: 'enum', enum: TaskPriority, default: TaskPriority.NORMAL })
  priority!: TaskPriority;

  @Column({ type: 'date', name: 'due_date', nullable: true })
  dueDate?: string | null;

  @Column({ type: 'char', length: 36, name: 'assignee_id', nullable: true })
  assigneeId?: string | null;

  @Column({
    type: 'enum',
    enum: LinkedEntityType,
    name: 'linked_entity_type',
    default: LinkedEntityType.MANUAL,
  })
  linkedEntityType!: LinkedEntityType;

  @Column({ type: 'char', length: 36, name: 'linked_entity_id', nullable: true })
  linkedEntityId?: string | null;

  @Column({ type: 'varchar', length: 64, name: 'cycle_key', nullable: true })
  cycleKey?: string | null;

  @Column({ type: 'boolean', name: 'auto_generated', default: false })
  autoGenerated!: boolean;

  @Column({ type: 'datetime', precision: 6, name: 'completed_at', nullable: true })
  completedAt?: Date | null;
}
