import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import {
  LinkedEntityType,
  Task,
  TaskStatus,
} from '../../database/entities/task.entity';
import { CreateTaskDto, UpdateTaskDto } from './dto/upsert-task.dto';
import { AuthenticatedUser } from '../../common/decorators/current-user.decorator';
import { AuditService } from '../audit/audit.service';

export interface AutoTaskInput {
  organizationId: string;
  clientId?: string | null;
  title: string;
  description?: string;
  dueDate?: string | null;
  assigneeId?: string | null;
  linkedEntityType: LinkedEntityType;
  linkedEntityId: string;
  cycleKey: string;
  status?: TaskStatus;
}

@Injectable()
export class TasksService {
  constructor(
    @InjectRepository(Task) private readonly repo: Repository<Task>,
    private readonly audit: AuditService,
  ) {}

  list(orgId: string) {
    return this.repo.find({
      where: { organizationId: orgId },
      order: { dueDate: 'ASC', createdAt: 'DESC' },
    });
  }

  async findOne(orgId: string, id: string) {
    const t = await this.repo.findOne({ where: { id, organizationId: orgId } });
    if (!t) throw new NotFoundException();
    return t;
  }

  async create(user: AuthenticatedUser, dto: CreateTaskDto, ip?: string) {
    const t = this.repo.create({
      organizationId: user.organizationId,
      title: dto.title,
      description: dto.description,
      status: dto.status ?? TaskStatus.TODO,
      priority: dto.priority,
      dueDate: dto.dueDate,
      assigneeId: dto.assigneeId,
      clientId: dto.clientId,
      linkedEntityType: LinkedEntityType.MANUAL,
      autoGenerated: false,
      createdBy: user.userId,
      updatedBy: user.userId,
    });
    const saved = await this.repo.save(t);
    await this.audit.record({
      organizationId: user.organizationId, actorId: user.userId,
      action: 'create_task', entity: 'Task', entityId: saved.id, after: saved, ip,
    });
    return saved;
  }

  async update(user: AuthenticatedUser, id: string, dto: UpdateTaskDto, ip?: string) {
    const t = await this.findOne(user.organizationId, id);
    const before = { ...t };
    Object.assign(t, dto, { updatedBy: user.userId });
    if (dto.status === TaskStatus.DONE) t.completedAt = new Date();
    const saved = await this.repo.save(t);
    await this.audit.record({
      organizationId: user.organizationId, actorId: user.userId,
      action: 'update_task', entity: 'Task', entityId: id,
      before, after: saved, ip,
    });
    return saved;
  }

  /** Idempotent — uses unique constraint on (org, linkedType, linkedId, cycleKey). */
  async upsertAuto(input: AutoTaskInput): Promise<Task> {
    const existing = await this.repo.findOne({
      where: {
        organizationId: input.organizationId,
        linkedEntityType: input.linkedEntityType,
        linkedEntityId: input.linkedEntityId,
        cycleKey: input.cycleKey,
      },
    });
    if (existing) return existing;
    const t = this.repo.create({
      organizationId: input.organizationId,
      clientId: input.clientId ?? null,
      title: input.title,
      description: input.description ?? null,
      status: input.status ?? TaskStatus.TODO,
      dueDate: input.dueDate ?? null,
      assigneeId: input.assigneeId ?? null,
      linkedEntityType: input.linkedEntityType,
      linkedEntityId: input.linkedEntityId,
      cycleKey: input.cycleKey,
      autoGenerated: true,
    });
    return this.repo.save(t);
  }

  /** Used by scheduler when invoice/cycle close. */
  async closeForLink(orgId: string, type: LinkedEntityType, linkedId: string, cycleKey: string) {
    const t = await this.repo.findOne({
      where: { organizationId: orgId, linkedEntityType: type, linkedEntityId: linkedId, cycleKey },
    });
    if (!t) return null;
    t.status = TaskStatus.DONE;
    t.completedAt = new Date();
    return this.repo.save(t);
  }

  async findByLink(orgId: string, type: LinkedEntityType, linkedId: string, cycleKey: string) {
    return this.repo.findOne({
      where: { organizationId: orgId, linkedEntityType: type, linkedEntityId: linkedId, cycleKey },
    });
  }

  async moveToInProgress(orgId: string, type: LinkedEntityType, linkedId: string, cycleKey: string) {
    const t = await this.findByLink(orgId, type, linkedId, cycleKey);
    if (!t || t.status === TaskStatus.DONE) return null;
    t.status = TaskStatus.IN_PROGRESS;
    return this.repo.save(t);
  }

  async moveToOverdue(orgId: string, type: LinkedEntityType, linkedId: string, cycleKey: string) {
    const t = await this.findByLink(orgId, type, linkedId, cycleKey);
    if (!t || t.status === TaskStatus.DONE) return null;
    t.status = TaskStatus.OVERDUE;
    return this.repo.save(t);
  }
}
