import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '@/shared/api/client';
import { fmtDate } from '@/shared/lib/format-date';
import { Modal } from '@/shared/ui/Modal';
import { ConfirmDelete } from '@/shared/ui/ConfirmDelete';
import { Field } from '@/shared/ui/Field';

type Status = 'BACKLOG' | 'TODO' | 'IN_PROGRESS' | 'WAITING_ON_CLIENT' | 'OVERDUE' | 'DONE';
type Priority = 'LOW' | 'NORMAL' | 'HIGH' | 'URGENT';
const COLUMNS: { status: Status; title: string; tone: string }[] = [
  { status: 'TODO', title: 'To-Do', tone: 'bg-amber-50 border-amber-200' },
  { status: 'IN_PROGRESS', title: 'In Progress', tone: 'bg-blue-50 border-blue-200' },
  { status: 'WAITING_ON_CLIENT', title: 'Waiting on Client', tone: 'bg-purple-50 border-purple-200' },
  { status: 'OVERDUE', title: 'Overdue', tone: 'bg-red-50 border-red-200' },
  { status: 'DONE', title: 'Done', tone: 'bg-green-50 border-green-200' },
];
const ALL_STATUSES: Status[] = ['BACKLOG', 'TODO', 'IN_PROGRESS', 'WAITING_ON_CLIENT', 'OVERDUE', 'DONE'];
const PRIORITIES: Priority[] = ['LOW', 'NORMAL', 'HIGH', 'URGENT'];

interface Task {
  id: string;
  title: string;
  description?: string | null;
  status: Status;
  priority: Priority;
  dueDate?: string | null;
  clientId?: string | null;
  assigneeId?: string | null;
  linkedEntityType: string;
  linkedEntityId?: string | null;
  autoGenerated: boolean;
}

interface Form {
  title: string;
  description: string;
  status: Status;
  priority: Priority;
  dueDate: string;
}

const EMPTY: Form = { title: '', description: '', status: 'TODO', priority: 'NORMAL', dueDate: '' };

export function TaskBoard() {
  const qc = useQueryClient();
  const tasks = useQuery({
    queryKey: ['tasks'],
    queryFn: async (): Promise<Task[]> => (await api.get('/tasks')).data,
    refetchInterval: 10_000,
  });

  const [modal, setModal] = useState<{ id: string | null } | null>(null);
  const [form, setForm] = useState<Form>(EMPTY);
  const [confirmId, setConfirmId] = useState<string | null>(null);

  const upsert = useMutation({
    mutationFn: async () => {
      const body: Partial<Form> = {
        title: form.title,
        description: form.description || undefined,
        status: form.status,
        priority: form.priority,
        dueDate: form.dueDate || undefined,
      };
      return modal?.id
        ? (await api.patch(`/tasks/${modal.id}`, body)).data
        : (await api.post('/tasks', body)).data;
    },
    onSuccess: () => { qc.invalidateQueries({ queryKey: ['tasks'] }); setModal(null); setForm(EMPTY); },
  });

  const update = useMutation({
    mutationFn: async (vars: { id: string; patch: Partial<Task> }) =>
      (await api.patch(`/tasks/${vars.id}`, vars.patch)).data,
    onSuccess: () => qc.invalidateQueries({ queryKey: ['tasks'] }),
  });

  const del = useMutation({
    mutationFn: async (id: string) => api.delete(`/tasks/${id}`),
    onSuccess: () => { qc.invalidateQueries({ queryKey: ['tasks'] }); setConfirmId(null); },
  });

  const runScheduler = useMutation({
    mutationFn: async () => (await api.post('/scheduler/run-now')).data,
    onSuccess: () => qc.invalidateQueries({ queryKey: ['tasks'] }),
  });

  function openNew() {
    setForm(EMPTY);
    setModal({ id: null });
  }
  function openEdit(t: Task) {
    setForm({
      title: t.title,
      description: t.description ?? '',
      status: t.status,
      priority: t.priority,
      dueDate: t.dueDate ?? '',
    });
    setModal({ id: t.id });
  }

  return (
    <div className="space-y-4">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-semibold">Task board</h1>
          <p className="text-slate-500">Auto-generated from renewals + compliance. Edit or delete any card.</p>
        </div>
        <div className="flex gap-2">
          <button className="btn btn-secondary" disabled={runScheduler.isPending} onClick={() => runScheduler.mutate()}>
            {runScheduler.isPending ? 'Scanning…' : 'Run scheduler'}
          </button>
          <button className="btn btn-primary" onClick={openNew}>+ New task</button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-5 gap-3 overflow-auto">
        {COLUMNS.map((col) => {
          const cards = tasks.data?.filter((t) => t.status === col.status) ?? [];
          return (
            <div key={col.status} className={`rounded-lg border ${col.tone} min-h-[300px]`}>
              <div className="px-3 py-2 border-b flex justify-between items-center">
                <span className="font-medium text-sm">{col.title}</span>
                <span className="text-xs text-slate-500">{cards.length}</span>
              </div>
              <div className="p-2 space-y-2">
                {cards.map((t) => (
                  <div key={t.id} className="rounded-md bg-white border border-slate-200 p-2 text-sm shadow-sm">
                    <div className="font-medium mb-1 leading-snug">{t.title}</div>
                    <div className="flex items-center justify-between text-xs text-slate-500">
                      <span>
                        {t.linkedEntityType}
                        {t.autoGenerated && ' · auto'}
                      </span>
                      <span>{fmtDate(t.dueDate ?? null)}</span>
                    </div>
                    <select
                      className="input mt-2 py-1 text-xs"
                      value={t.status}
                      onChange={(e) => update.mutate({ id: t.id, patch: { status: e.target.value as Status } })}
                    >
                      {ALL_STATUSES.map((s) => <option key={s} value={s}>{s.replaceAll('_', ' ')}</option>)}
                    </select>
                    <div className="flex gap-1 mt-1">
                      <button className="btn btn-secondary py-1 text-xs flex-1" onClick={() => openEdit(t)}>Edit</button>
                      <button className="btn btn-danger py-1 text-xs flex-1" onClick={() => setConfirmId(t.id)}>Delete</button>
                    </div>
                  </div>
                ))}
                {cards.length === 0 && <div className="text-xs text-slate-400 px-2 py-4 text-center">—</div>}
              </div>
            </div>
          );
        })}
      </div>

      <Modal
        open={!!modal}
        onClose={() => setModal(null)}
        title={modal?.id ? 'Edit task' : 'New task'}
        footer={
          <>
            <button className="btn btn-secondary" onClick={() => setModal(null)}>Cancel</button>
            <button className="btn btn-primary" disabled={!form.title || upsert.isPending} onClick={() => upsert.mutate()}>
              {upsert.isPending ? 'Saving…' : 'Save'}
            </button>
          </>
        }
      >
        <Field label="Title" required>
          <input className="input" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} />
        </Field>
        <Field label="Description">
          <textarea className="input min-h-[80px]" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} />
        </Field>
        <div className="grid grid-cols-3 gap-3">
          <Field label="Status">
            <select className="input" value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as Status })}>
              {ALL_STATUSES.map((s) => <option key={s} value={s}>{s.replaceAll('_', ' ')}</option>)}
            </select>
          </Field>
          <Field label="Priority">
            <select className="input" value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value as Priority })}>
              {PRIORITIES.map((p) => <option key={p} value={p}>{p}</option>)}
            </select>
          </Field>
          <Field label="Due date">
            <input className="input" type="date" value={form.dueDate} onChange={(e) => setForm({ ...form, dueDate: e.target.value })} />
          </Field>
        </div>
      </Modal>

      <ConfirmDelete
        open={!!confirmId}
        onClose={() => setConfirmId(null)}
        onConfirm={() => confirmId && del.mutate(confirmId)}
        title="Delete task?"
        busy={del.isPending}
      />
    </div>
  );
}
