import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '@/shared/api/client';
import { fmtDate } from '@/shared/lib/format-date';

type Status = 'BACKLOG' | 'TODO' | 'IN_PROGRESS' | 'WAITING_ON_CLIENT' | 'OVERDUE' | 'DONE';
const COLUMNS: { status: Status; title: string; tone: string }[] = [
  { status: 'TODO', title: 'To-Do', tone: 'bg-amber-50 border-amber-200' },
  { status: 'IN_PROGRESS', title: 'In Progress', tone: 'bg-blue-50 border-blue-200' },
  { status: 'WAITING_ON_CLIENT', title: 'Waiting on Client', tone: 'bg-purple-50 border-purple-200' },
  { status: 'OVERDUE', title: 'Overdue', tone: 'bg-red-50 border-red-200' },
  { status: 'DONE', title: 'Done', tone: 'bg-green-50 border-green-200' },
];

interface Task {
  id: string;
  title: string;
  description?: string | null;
  status: Status;
  dueDate?: string | null;
  linkedEntityType: string;
  linkedEntityId?: string | null;
  autoGenerated: boolean;
}

export function TaskBoard() {
  const qc = useQueryClient();
  const tasks = useQuery({
    queryKey: ['tasks'],
    queryFn: async (): Promise<Task[]> => (await api.get('/tasks')).data,
    refetchInterval: 10_000,
  });

  const update = useMutation({
    mutationFn: async (vars: { id: string; patch: Partial<Task> }) =>
      (await api.patch(`/tasks/${vars.id}`, vars.patch)).data,
    onSuccess: () => qc.invalidateQueries({ queryKey: ['tasks'] }),
  });

  const runScheduler = useMutation({
    mutationFn: async () => (await api.post('/scheduler/run-now')).data,
    onSuccess: () => qc.invalidateQueries({ queryKey: ['tasks'] }),
  });

  return (
    <div className="space-y-4">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-semibold">Task board</h1>
          <p className="text-slate-500">Auto-generated from renewals + compliance. Drop a card by changing status.</p>
        </div>
        <button className="btn btn-secondary" disabled={runScheduler.isPending} onClick={() => runScheduler.mutate()}>
          {runScheduler.isPending ? 'Scanning…' : 'Run scheduler now'}
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-5 gap-3 overflow-auto">
        {COLUMNS.map((col) => {
          const cards = tasks.data?.filter((t) => t.status === col.status) ?? [];
          return (
            <div key={col.status} className={`rounded-lg border ${col.tone} min-h-[300px]`}>
              <div className="px-3 py-2 border-b flex justify-between items-center">
                <span className="font-medium text-sm">{col.title}</span>
                <span className="text-xs text-slate-500">{cards.length}</span>
              </div>
              <div className="p-2 space-y-2">
                {cards.map((t) => (
                  <div key={t.id} className="rounded-md bg-white border border-slate-200 p-2 text-sm shadow-sm">
                    <div className="font-medium mb-1 leading-snug">{t.title}</div>
                    <div className="flex items-center justify-between text-xs text-slate-500">
                      <span>
                        {t.linkedEntityType}
                        {t.autoGenerated && ' · auto'}
                      </span>
                      <span>{fmtDate(t.dueDate ?? null)}</span>
                    </div>
                    <select
                      className="input mt-2 py-1 text-xs"
                      value={t.status}
                      onChange={(e) => update.mutate({ id: t.id, patch: { status: e.target.value as Status } })}
                    >
                      {COLUMNS.map((c) => <option key={c.status} value={c.status}>{c.title}</option>)}
                      <option value="BACKLOG">Backlog</option>
                    </select>
                  </div>
                ))}
                {cards.length === 0 && <div className="text-xs text-slate-400 px-2 py-4 text-center">—</div>}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
